name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'
    env:
      HATENA_API_CONSUMER_KEY:    ${{ secrets.HATENA_API_CONSUMER_KEY }}
      HATENA_API_CONSUMER_SECRET: ${{ secrets.HATENA_API_CONSUMER_SECRET }}
      HATENA_API_REQUEST_TOKEN:   ${{ secrets.HATENA_API_REQUEST_TOKEN }}
      HATENA_API_REQUEST_SECRET:  ${{ secrets.HATENA_API_REQUEST_SECRET }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
